### ISSUE TITLE
Ports configuration doesn't seem to persist over restarts.

### ISSUE THREAD

**Issue by OlivierKessler01** [realies/soulseek-docker#32]
Hi there,

I'm using the exact same configuration you're proposing in the doc, but can't seem to have the Soulseek listening port configuration persist over container restarts. It keep using different ports over and over again. Also the /data/.SoulseekQt folder stays empty.

```
version: "2.1"
services:
  soulseek:
    image: realies/soulseek
    container_name: soulseek
    environment:
      - PUID=1000
      - PGID=1000
      - resize=scale
      - resolution=1280x720
    volumes:
      - '/srv/data/music:/data/music'
      - '/srv/data/soulseek/appdata:/data/.SoulseekQt'
      - '/srv/data/soulseek/downloads:/data/Soulseek Downloads'
      - '/srv/data/soulseek/logs:/data/Soulseek Chat Logs'
    ports:
      - 6080:6080
      - 53028:53028
      - 53029:53029 
    restart: always
```

Thanks in advance :)
