### ISSUE TITLE
reverse proxy config

### ISSUE THREAD

**Issue by sintaxx** [realies/soulseek-docker#33]
so I've got the container up and running and it works great but when I try to add it to my nginx reverse proxy, the vnc server can't connect, any ideas on how to resolve this? i'll paste below my config statements from compose and the proxy conf

```
soulseek:
    container_name: soulseek
    restart: always
    volumes:
      - '${DOCKERCONFDIR}/slsk/appdata:/data/.SoulseekQt'
      - '${DOCKERCONFDIR}/slsk/downloads:/data/Soulseek Downloads'
      - '${DOCKERCONFDIR}/slsk/logs:/data/Soulseek Chat Logs'
    environment:
      - pgid=1000
      - puid=1000
      - resize=scale
      - resolution=1280x720
    ports:
      - '6080:6080'
    image: realies/soulseek
```

```
    #include /config/nginx/authelia-server.conf;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable the next two lines for ldap auth
        #auth_request /auth;
        #error_page 401 =200 /ldaplogin;

        # enable for Authelia
        #include /config/nginx/authelia-location.conf;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app soulseek;
        set $upstream_port 6080;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    }

    location /websockify {
        include /config/nginx/proxy.conf;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_pass $upstream_proto://$upstream_app:$upstream_port/;
    }

}


```

![image](https://user-images.githubusercontent.com/23103088/121814829-0db77700-cc41-11eb-95fd-f467a428e940.png)
