### ISSUE TITLE
Add build+push pipeline

### ISSUE THREAD

**Issue by javydekoning** [realies/soulseek-docker#38]
Hi, 

It seems that this is a fairly outdated container. Perhaps we can add a workflow to automatically rebuild and publish?

Something like this might do...

`cat .github/workflows/container.yml` : 

```yaml
name: 'build'

on:
  push:
    branches:
    - master
  schedule:
    - cron: "0 9 * * *"
jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          username: "realies"
          password: ${{ secrets.PAT }}
          repository: realies/soulseek-docker
          tags: latest
```

Also consider adding versions as ARG in `Dockerfile` to do easier updates. 

e.g. 

```
# Define Args for the needed to add dependencies
ARG NOVNC_VERSION=1.3.0
ARG NOVNC_PACKAGE_URL=https://github.com/novnc/noVNC/archive/refs/tags/v${NOVNC_VERSION}.tar.gz

ARG FA_VERSION=5.15.4
ARG FA_PACKAGE_URL=https://use.fontawesome.com/releases/v${FA_VERSION}/svgs/solid/cloud-download-alt.svg
```

This would also close #30
