### ISSUE TITLE
VNCPWD environment variable not working; container fails to launch

### ISSUE THREAD

**Issue by DiamondShark** [realies/soulseek-docker#50]
Hi! When I try to build from a docker-compose file, here's the error that I get:

soulseek       | /init.sh: 14: vncpasswd: not found
soulseek exited with code 127

Here's the sample of the docker compose file!
```
soulseek:
    image: realies/soulseek
    container_name: soulseek
    environment:
      - VNCPWD=thisismysecretpassword
      # media group
      - PGID=1014
      # soulseek user
      - PUID=157
    volumes:
      - localdrive/data:/data/.SoulseekQt
      - localdrive/downloads:/Soulseek Downloads
      - localdrive/shared:/data/Soulseek Shared Folder
      - localdrive/logs:/data/Soulseek Chat Logs
    restart: unless-stopped
```
