### ISSUE TITLE
Changes aren't persisten after container restart.

### ISSUE THREAD

**Issue by hrmtc** [realies/soulseek-docker#57]
Hi.

I don't know what I'm doing wrong:

I've double checked my volumes mapping, but after restart the container, the config is not saved.

Thanks.

This is my docker-compose file:

```
  soulseek:
    image: realies/soulseek
    container_name: soulseek
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "20"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Buenos_Aires
      - UMASK=002
    ports:
      - 6080:6080
    volumes:
      - /docker/appdata/soulseek/appdata:/data/.SoulseekQt
      - /docker/appdata/soulseek/downloads:/data/Soulseek Downloads 
      - /mnt/NAS/Descargas/Soulseek:/mnt/downloads
      - /docker/appdata/soulseek/shared:/data/Soulseek Shared Folder
      - /docker/appdata/soulseek/logs:/data/Soulseek Chat Logs

```
